package com.ericsson.ms.module.entity.entities;
// Generated Feb 17, 2021 5:45:34 PM by Hibernate Tools 5.4.27.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EnvBb generated by hbm2java
 */
@Entity
@Table(name="env_bb"
    ,schema="public"
)
public class EnvBb  implements java.io.Serializable {


     private String envBbid;
     private String envBbname;
     private String envBbdesc;
     private String envBbstatus;
     private Short itemSeq;
     private Set<EnvBbcomp> envBbcomps = new HashSet<EnvBbcomp>(0);

    public EnvBb() {
    }

	
    public EnvBb(String envBbid, String envBbname, String envBbdesc, String envBbstatus) {
        this.envBbid = envBbid;
        this.envBbname = envBbname;
        this.envBbdesc = envBbdesc;
        this.envBbstatus = envBbstatus;
    }
    public EnvBb(String envBbid, String envBbname, String envBbdesc, String envBbstatus, Short itemSeq, Set<EnvBbcomp> envBbcomps) {
       this.envBbid = envBbid;
       this.envBbname = envBbname;
       this.envBbdesc = envBbdesc;
       this.envBbstatus = envBbstatus;
       this.itemSeq = itemSeq;
       this.envBbcomps = envBbcomps;
    }
   
     @Id 

    
    @Column(name="env_bbid", unique=true, nullable=false, length=20)
    public String getEnvBbid() {
        return this.envBbid;
    }
    
    public void setEnvBbid(String envBbid) {
        this.envBbid = envBbid;
    }

    
    @Column(name="env_bbname", nullable=false, length=100)
    public String getEnvBbname() {
        return this.envBbname;
    }
    
    public void setEnvBbname(String envBbname) {
        this.envBbname = envBbname;
    }

    
    @Column(name="env_bbdesc", nullable=false)
    public String getEnvBbdesc() {
        return this.envBbdesc;
    }
    
    public void setEnvBbdesc(String envBbdesc) {
        this.envBbdesc = envBbdesc;
    }

    
    @Column(name="env_bbstatus", nullable=false)
    public String getEnvBbstatus() {
        return this.envBbstatus;
    }
    
    public void setEnvBbstatus(String envBbstatus) {
        this.envBbstatus = envBbstatus;
    }

    
    @Column(name="item_seq")
    public Short getItemSeq() {
        return this.itemSeq;
    }
    
    public void setItemSeq(Short itemSeq) {
        this.itemSeq = itemSeq;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="envBb")
    public Set<EnvBbcomp> getEnvBbcomps() {
        return this.envBbcomps;
    }
    
    public void setEnvBbcomps(Set<EnvBbcomp> envBbcomps) {
        this.envBbcomps = envBbcomps;
    }




}


