package com.ericsson.ms.module.entity.entities;
// Generated Feb 17, 2021 5:45:34 PM by Hibernate Tools 5.4.27.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EnvBbcomp generated by hbm2java
 */
@Entity
@Table(name="env_bbcomp"
    ,schema="public"
)
public class EnvBbcomp  implements java.io.Serializable {


     private String envCompid;
     private EnvBb envBb;
     private String envCompname;
     private String envCompdesc;
     private String envCompstatus;
     private String envCompType;
     private Integer itemSeq;
     private String envPlatform;
     private Set<EnvCompspec> envCompspecs = new HashSet<EnvCompspec>(0);
     private Set<EnvBbdepcomp> envBbdepcompsForEnvDepcompid = new HashSet<EnvBbdepcomp>(0);
     private Set<EnvBbdepcomp> envBbdepcompsForEnvCompid = new HashSet<EnvBbdepcomp>(0);
     private Set<EnvReqcomp> envReqcomps = new HashSet<EnvReqcomp>(0);

    public EnvBbcomp() {
    }

	
    public EnvBbcomp(String envCompid, EnvBb envBb, String envCompname, String envCompdesc, String envCompstatus) {
        this.envCompid = envCompid;
        this.envBb = envBb;
        this.envCompname = envCompname;
        this.envCompdesc = envCompdesc;
        this.envCompstatus = envCompstatus;
    }
    public EnvBbcomp(String envCompid, EnvBb envBb, String envCompname, String envCompdesc, String envCompstatus, String envCompType, Integer itemSeq, String envPlatform, Set<EnvCompspec> envCompspecs, Set<EnvBbdepcomp> envBbdepcompsForEnvDepcompid, Set<EnvBbdepcomp> envBbdepcompsForEnvCompid, Set<EnvReqcomp> envReqcomps) {
       this.envCompid = envCompid;
       this.envBb = envBb;
       this.envCompname = envCompname;
       this.envCompdesc = envCompdesc;
       this.envCompstatus = envCompstatus;
       this.envCompType = envCompType;
       this.itemSeq = itemSeq;
       this.envPlatform = envPlatform;
       this.envCompspecs = envCompspecs;
       this.envBbdepcompsForEnvDepcompid = envBbdepcompsForEnvDepcompid;
       this.envBbdepcompsForEnvCompid = envBbdepcompsForEnvCompid;
       this.envReqcomps = envReqcomps;
    }
   
     @Id 

    
    @Column(name="env_compid", unique=true, nullable=false, length=20)
    public String getEnvCompid() {
        return this.envCompid;
    }
    
    public void setEnvCompid(String envCompid) {
        this.envCompid = envCompid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="env_bbid", nullable=false)
    public EnvBb getEnvBb() {
        return this.envBb;
    }
    
    public void setEnvBb(EnvBb envBb) {
        this.envBb = envBb;
    }

    
    @Column(name="env_compname", nullable=false, length=100)
    public String getEnvCompname() {
        return this.envCompname;
    }
    
    public void setEnvCompname(String envCompname) {
        this.envCompname = envCompname;
    }

    
    @Column(name="env_compdesc", nullable=false)
    public String getEnvCompdesc() {
        return this.envCompdesc;
    }
    
    public void setEnvCompdesc(String envCompdesc) {
        this.envCompdesc = envCompdesc;
    }

    
    @Column(name="env_compstatus", nullable=false)
    public String getEnvCompstatus() {
        return this.envCompstatus;
    }
    
    public void setEnvCompstatus(String envCompstatus) {
        this.envCompstatus = envCompstatus;
    }

    
    @Column(name="env_comp_type", length=10)
    public String getEnvCompType() {
        return this.envCompType;
    }
    
    public void setEnvCompType(String envCompType) {
        this.envCompType = envCompType;
    }

    
    @Column(name="item_seq")
    public Integer getItemSeq() {
        return this.itemSeq;
    }
    
    public void setItemSeq(Integer itemSeq) {
        this.itemSeq = itemSeq;
    }

    
    @Column(name="env_platform", length=20)
    public String getEnvPlatform() {
        return this.envPlatform;
    }
    
    public void setEnvPlatform(String envPlatform) {
        this.envPlatform = envPlatform;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="envBbcomp")
    public Set<EnvCompspec> getEnvCompspecs() {
        return this.envCompspecs;
    }
    
    public void setEnvCompspecs(Set<EnvCompspec> envCompspecs) {
        this.envCompspecs = envCompspecs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="envBbcompByEnvDepcompid")
    public Set<EnvBbdepcomp> getEnvBbdepcompsForEnvDepcompid() {
        return this.envBbdepcompsForEnvDepcompid;
    }
    
    public void setEnvBbdepcompsForEnvDepcompid(Set<EnvBbdepcomp> envBbdepcompsForEnvDepcompid) {
        this.envBbdepcompsForEnvDepcompid = envBbdepcompsForEnvDepcompid;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="envBbcompByEnvCompid")
    public Set<EnvBbdepcomp> getEnvBbdepcompsForEnvCompid() {
        return this.envBbdepcompsForEnvCompid;
    }
    
    public void setEnvBbdepcompsForEnvCompid(Set<EnvBbdepcomp> envBbdepcompsForEnvCompid) {
        this.envBbdepcompsForEnvCompid = envBbdepcompsForEnvCompid;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="envBbcomp")
    public Set<EnvReqcomp> getEnvReqcomps() {
        return this.envReqcomps;
    }
    
    public void setEnvReqcomps(Set<EnvReqcomp> envReqcomps) {
        this.envReqcomps = envReqcomps;
    }




}


