package com.ericsson.ms.module.entity.entities;
// Generated Feb 17, 2021 5:45:34 PM by Hibernate Tools 5.4.27.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EnvBbdepcomp generated by hbm2java
 */
@Entity
@Table(name="env_bbdepcomp"
    ,schema="public"
)
public class EnvBbdepcomp  implements java.io.Serializable {


     private String envCompassoid;
     private EnvBbcomp envBbcompByEnvDepcompid;
     private EnvBbcomp envBbcompByEnvCompid;

    public EnvBbdepcomp() {
    }

    public EnvBbdepcomp(String envCompassoid, EnvBbcomp envBbcompByEnvDepcompid, EnvBbcomp envBbcompByEnvCompid) {
       this.envCompassoid = envCompassoid;
       this.envBbcompByEnvDepcompid = envBbcompByEnvDepcompid;
       this.envBbcompByEnvCompid = envBbcompByEnvCompid;
    }
   
     @Id 

    
    @Column(name="env_compassoid", unique=true, nullable=false, length=20)
    public String getEnvCompassoid() {
        return this.envCompassoid;
    }
    
    public void setEnvCompassoid(String envCompassoid) {
        this.envCompassoid = envCompassoid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="env_depcompid", nullable=false)
    public EnvBbcomp getEnvBbcompByEnvDepcompid() {
        return this.envBbcompByEnvDepcompid;
    }
    
    public void setEnvBbcompByEnvDepcompid(EnvBbcomp envBbcompByEnvDepcompid) {
        this.envBbcompByEnvDepcompid = envBbcompByEnvDepcompid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="env_compid", nullable=false)
    public EnvBbcomp getEnvBbcompByEnvCompid() {
        return this.envBbcompByEnvCompid;
    }
    
    public void setEnvBbcompByEnvCompid(EnvBbcomp envBbcompByEnvCompid) {
        this.envBbcompByEnvCompid = envBbcompByEnvCompid;
    }




}


