package com.ericsson.ms.module.entity.entities;
// Generated Feb 17, 2021 5:45:34 PM by Hibernate Tools 5.4.27.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EnvCompspec generated by hbm2java
 */
@Entity
@Table(name="env_compspec"
    ,schema="public"
)
public class EnvCompspec  implements java.io.Serializable {


     private String envSpecid;
     private EnvBbcomp envBbcomp;
     private String envSpecname;
     private String envSpectype;
     private String envSpecvalidation;
     private String envSpecdesc;
     private String envSpecvalues;
     private String envCompstatus;
     private Set<EnvCompdepspec> envCompdepspecsForEnvSpecid = new HashSet<EnvCompdepspec>(0);
     private Set<EnvReqspec> envReqspecs = new HashSet<EnvReqspec>(0);
     private Set<EnvCompdepspec> envCompdepspecsForEnvDepspecid = new HashSet<EnvCompdepspec>(0);

    public EnvCompspec() {
    }

	
    public EnvCompspec(String envSpecid, EnvBbcomp envBbcomp, String envSpecname, String envSpectype, String envSpecvalidation, String envSpecdesc, String envSpecvalues, String envCompstatus) {
        this.envSpecid = envSpecid;
        this.envBbcomp = envBbcomp;
        this.envSpecname = envSpecname;
        this.envSpectype = envSpectype;
        this.envSpecvalidation = envSpecvalidation;
        this.envSpecdesc = envSpecdesc;
        this.envSpecvalues = envSpecvalues;
        this.envCompstatus = envCompstatus;
    }
    public EnvCompspec(String envSpecid, EnvBbcomp envBbcomp, String envSpecname, String envSpectype, String envSpecvalidation, String envSpecdesc, String envSpecvalues, String envCompstatus, Set<EnvCompdepspec> envCompdepspecsForEnvSpecid, Set<EnvReqspec> envReqspecs, Set<EnvCompdepspec> envCompdepspecsForEnvDepspecid) {
       this.envSpecid = envSpecid;
       this.envBbcomp = envBbcomp;
       this.envSpecname = envSpecname;
       this.envSpectype = envSpectype;
       this.envSpecvalidation = envSpecvalidation;
       this.envSpecdesc = envSpecdesc;
       this.envSpecvalues = envSpecvalues;
       this.envCompstatus = envCompstatus;
       this.envCompdepspecsForEnvSpecid = envCompdepspecsForEnvSpecid;
       this.envReqspecs = envReqspecs;
       this.envCompdepspecsForEnvDepspecid = envCompdepspecsForEnvDepspecid;
    }
   
     @Id 

    
    @Column(name="env_specid", unique=true, nullable=false, length=30)
    public String getEnvSpecid() {
        return this.envSpecid;
    }
    
    public void setEnvSpecid(String envSpecid) {
        this.envSpecid = envSpecid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="env_compid", nullable=false)
    public EnvBbcomp getEnvBbcomp() {
        return this.envBbcomp;
    }
    
    public void setEnvBbcomp(EnvBbcomp envBbcomp) {
        this.envBbcomp = envBbcomp;
    }

    
    @Column(name="env_specname", nullable=false, length=100)
    public String getEnvSpecname() {
        return this.envSpecname;
    }
    
    public void setEnvSpecname(String envSpecname) {
        this.envSpecname = envSpecname;
    }

    
    @Column(name="env_spectype", nullable=false, length=10)
    public String getEnvSpectype() {
        return this.envSpectype;
    }
    
    public void setEnvSpectype(String envSpectype) {
        this.envSpectype = envSpectype;
    }

    
    @Column(name="env_specvalidation", nullable=false)
    public String getEnvSpecvalidation() {
        return this.envSpecvalidation;
    }
    
    public void setEnvSpecvalidation(String envSpecvalidation) {
        this.envSpecvalidation = envSpecvalidation;
    }

    
    @Column(name="env_specdesc", nullable=false)
    public String getEnvSpecdesc() {
        return this.envSpecdesc;
    }
    
    public void setEnvSpecdesc(String envSpecdesc) {
        this.envSpecdesc = envSpecdesc;
    }

    
    @Column(name="env_specvalues", nullable=false)
    public String getEnvSpecvalues() {
        return this.envSpecvalues;
    }
    
    public void setEnvSpecvalues(String envSpecvalues) {
        this.envSpecvalues = envSpecvalues;
    }

    
    @Column(name="env_compstatus", nullable=false, length=100)
    public String getEnvCompstatus() {
        return this.envCompstatus;
    }
    
    public void setEnvCompstatus(String envCompstatus) {
        this.envCompstatus = envCompstatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="envCompspecByEnvSpecid")
    public Set<EnvCompdepspec> getEnvCompdepspecsForEnvSpecid() {
        return this.envCompdepspecsForEnvSpecid;
    }
    
    public void setEnvCompdepspecsForEnvSpecid(Set<EnvCompdepspec> envCompdepspecsForEnvSpecid) {
        this.envCompdepspecsForEnvSpecid = envCompdepspecsForEnvSpecid;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="envCompspec")
    public Set<EnvReqspec> getEnvReqspecs() {
        return this.envReqspecs;
    }
    
    public void setEnvReqspecs(Set<EnvReqspec> envReqspecs) {
        this.envReqspecs = envReqspecs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="envCompspecByEnvDepspecid")
    public Set<EnvCompdepspec> getEnvCompdepspecsForEnvDepspecid() {
        return this.envCompdepspecsForEnvDepspecid;
    }
    
    public void setEnvCompdepspecsForEnvDepspecid(Set<EnvCompdepspec> envCompdepspecsForEnvDepspecid) {
        this.envCompdepspecsForEnvDepspecid = envCompdepspecsForEnvDepspecid;
    }




}


