package com.ericsson.ms.module.entity.entities;
// Generated Feb 17, 2021 5:45:34 PM by Hibernate Tools 5.4.27.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EnvCompdepspec generated by hbm2java
 */
@Entity
@Table(name="env_compdepspec"
    ,schema="public"
)
public class EnvCompdepspec  implements java.io.Serializable {


     private String envSpecassoid;
     private EnvCompspec envCompspecByEnvSpecid;
     private EnvCompspec envCompspecByEnvDepspecid;

    public EnvCompdepspec() {
    }

    public EnvCompdepspec(String envSpecassoid, EnvCompspec envCompspecByEnvSpecid, EnvCompspec envCompspecByEnvDepspecid) {
       this.envSpecassoid = envSpecassoid;
       this.envCompspecByEnvSpecid = envCompspecByEnvSpecid;
       this.envCompspecByEnvDepspecid = envCompspecByEnvDepspecid;
    }
   
     @Id 

    
    @Column(name="env_specassoid", unique=true, nullable=false, length=20)
    public String getEnvSpecassoid() {
        return this.envSpecassoid;
    }
    
    public void setEnvSpecassoid(String envSpecassoid) {
        this.envSpecassoid = envSpecassoid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="env_specid", nullable=false)
    public EnvCompspec getEnvCompspecByEnvSpecid() {
        return this.envCompspecByEnvSpecid;
    }
    
    public void setEnvCompspecByEnvSpecid(EnvCompspec envCompspecByEnvSpecid) {
        this.envCompspecByEnvSpecid = envCompspecByEnvSpecid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="env_depspecid", nullable=false)
    public EnvCompspec getEnvCompspecByEnvDepspecid() {
        return this.envCompspecByEnvDepspecid;
    }
    
    public void setEnvCompspecByEnvDepspecid(EnvCompspec envCompspecByEnvDepspecid) {
        this.envCompspecByEnvDepspecid = envCompspecByEnvDepspecid;
    }




}


