package com.ericsson.ms.module.entity.entities;
// Generated Feb 17, 2021 5:45:34 PM by Hibernate Tools 5.4.27.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EnvReqspec generated by hbm2java
 */
@Entity
@Table(name="env_reqspec"
    ,schema="public"
)
public class EnvReqspec  implements java.io.Serializable {


     private String envReqspecid;
     private EnvCompspec envCompspec;
     private EnvReqcomp envReqcomp;
     private String envSpecvalue;

    public EnvReqspec() {
    }

    public EnvReqspec(String envReqspecid, EnvCompspec envCompspec, EnvReqcomp envReqcomp, String envSpecvalue) {
       this.envReqspecid = envReqspecid;
       this.envCompspec = envCompspec;
       this.envReqcomp = envReqcomp;
       this.envSpecvalue = envSpecvalue;
    }
   
     @Id 

    
    @Column(name="env_reqspecid", unique=true, nullable=false, length=20)
    public String getEnvReqspecid() {
        return this.envReqspecid;
    }
    
    public void setEnvReqspecid(String envReqspecid) {
        this.envReqspecid = envReqspecid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="env_specid", nullable=false)
    public EnvCompspec getEnvCompspec() {
        return this.envCompspec;
    }
    
    public void setEnvCompspec(EnvCompspec envCompspec) {
        this.envCompspec = envCompspec;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="env_reqcompid", nullable=false)
    public EnvReqcomp getEnvReqcomp() {
        return this.envReqcomp;
    }
    
    public void setEnvReqcomp(EnvReqcomp envReqcomp) {
        this.envReqcomp = envReqcomp;
    }

    
    @Column(name="env_specvalue", nullable=false)
    public String getEnvSpecvalue() {
        return this.envSpecvalue;
    }
    
    public void setEnvSpecvalue(String envSpecvalue) {
        this.envSpecvalue = envSpecvalue;
    }




}


