package com.ericsson.ms.module.entity.entities;
// Generated Feb 17, 2021 5:45:34 PM by Hibernate Tools 5.4.27.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EnvReq generated by hbm2java
 */
@Entity
@Table(name="env_req"
    ,schema="public"
)
public class EnvReq  implements java.io.Serializable {


     private String envReqid;
     private String envReqtitle;
     private String envReqproj;
     private String envReqacc;
     private String envReqdtl;
     private Date envReqcapdt;
     private Date envReqresubdt;
     private Date envReqcomdt;
     private String envReqsignum;
     private String envReqstatus;
     private String envReqstatdtl;
     private String envPlatform;
     private String envAccessid;
     private String envSecretkey;
     private byte[] envPpkfile;
     private Set<EnvReqcomp> envReqcomps = new HashSet<EnvReqcomp>(0);

    public EnvReq() {
    }

	
    public EnvReq(String envReqid, String envReqtitle, String envReqproj, String envReqacc, String envReqdtl, Date envReqcapdt, Date envReqresubdt, Date envReqcomdt, String envReqsignum, String envReqstatus, String envReqstatdtl) {
        this.envReqid = envReqid;
        this.envReqtitle = envReqtitle;
        this.envReqproj = envReqproj;
        this.envReqacc = envReqacc;
        this.envReqdtl = envReqdtl;
        this.envReqcapdt = envReqcapdt;
        this.envReqresubdt = envReqresubdt;
        this.envReqcomdt = envReqcomdt;
        this.envReqsignum = envReqsignum;
        this.envReqstatus = envReqstatus;
        this.envReqstatdtl = envReqstatdtl;
    }
    public EnvReq(String envReqid, String envReqtitle, String envReqproj, String envReqacc, String envReqdtl, Date envReqcapdt, Date envReqresubdt, Date envReqcomdt, String envReqsignum, String envReqstatus, String envReqstatdtl, String envPlatform, String envAccessid, String envSecretkey, byte[] envPpkfile, Set<EnvReqcomp> envReqcomps) {
       this.envReqid = envReqid;
       this.envReqtitle = envReqtitle;
       this.envReqproj = envReqproj;
       this.envReqacc = envReqacc;
       this.envReqdtl = envReqdtl;
       this.envReqcapdt = envReqcapdt;
       this.envReqresubdt = envReqresubdt;
       this.envReqcomdt = envReqcomdt;
       this.envReqsignum = envReqsignum;
       this.envReqstatus = envReqstatus;
       this.envReqstatdtl = envReqstatdtl;
       this.envPlatform = envPlatform;
       this.envAccessid = envAccessid;
       this.envSecretkey = envSecretkey;
       this.envPpkfile = envPpkfile;
       this.envReqcomps = envReqcomps;
    }
   
     @Id 

    
    @Column(name="env_reqid", unique=true, nullable=false, length=20)
    public String getEnvReqid() {
        return this.envReqid;
    }
    
    public void setEnvReqid(String envReqid) {
        this.envReqid = envReqid;
    }

    
    @Column(name="env_reqtitle", nullable=false, length=100)
    public String getEnvReqtitle() {
        return this.envReqtitle;
    }
    
    public void setEnvReqtitle(String envReqtitle) {
        this.envReqtitle = envReqtitle;
    }

    
    @Column(name="env_reqproj", nullable=false, length=100)
    public String getEnvReqproj() {
        return this.envReqproj;
    }
    
    public void setEnvReqproj(String envReqproj) {
        this.envReqproj = envReqproj;
    }

    
    @Column(name="env_reqacc", nullable=false, length=100)
    public String getEnvReqacc() {
        return this.envReqacc;
    }
    
    public void setEnvReqacc(String envReqacc) {
        this.envReqacc = envReqacc;
    }

    
    @Column(name="env_reqdtl", nullable=false)
    public String getEnvReqdtl() {
        return this.envReqdtl;
    }
    
    public void setEnvReqdtl(String envReqdtl) {
        this.envReqdtl = envReqdtl;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="env_reqcapdt", nullable=false, length=35)
    public Date getEnvReqcapdt() {
        return this.envReqcapdt;
    }
    
    public void setEnvReqcapdt(Date envReqcapdt) {
        this.envReqcapdt = envReqcapdt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="env_reqresubdt", nullable=false, length=35)
    public Date getEnvReqresubdt() {
        return this.envReqresubdt;
    }
    
    public void setEnvReqresubdt(Date envReqresubdt) {
        this.envReqresubdt = envReqresubdt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="env_reqcomdt", nullable=false, length=35)
    public Date getEnvReqcomdt() {
        return this.envReqcomdt;
    }
    
    public void setEnvReqcomdt(Date envReqcomdt) {
        this.envReqcomdt = envReqcomdt;
    }

    
    @Column(name="env_reqsignum", nullable=false, length=100)
    public String getEnvReqsignum() {
        return this.envReqsignum;
    }
    
    public void setEnvReqsignum(String envReqsignum) {
        this.envReqsignum = envReqsignum;
    }

    
    @Column(name="env_reqstatus", nullable=false, length=100)
    public String getEnvReqstatus() {
        return this.envReqstatus;
    }
    
    public void setEnvReqstatus(String envReqstatus) {
        this.envReqstatus = envReqstatus;
    }

    
    @Column(name="env_reqstatdtl", nullable=false)
    public String getEnvReqstatdtl() {
        return this.envReqstatdtl;
    }
    
    public void setEnvReqstatdtl(String envReqstatdtl) {
        this.envReqstatdtl = envReqstatdtl;
    }

    
    @Column(name="env_platform", length=20)
    public String getEnvPlatform() {
        return this.envPlatform;
    }
    
    public void setEnvPlatform(String envPlatform) {
        this.envPlatform = envPlatform;
    }

    
    @Column(name="env_accessid", length=50)
    public String getEnvAccessid() {
        return this.envAccessid;
    }
    
    public void setEnvAccessid(String envAccessid) {
        this.envAccessid = envAccessid;
    }

    
    @Column(name="env_secretkey", length=100)
    public String getEnvSecretkey() {
        return this.envSecretkey;
    }
    
    public void setEnvSecretkey(String envSecretkey) {
        this.envSecretkey = envSecretkey;
    }

    
    @Column(name="env_ppkfile")
    public byte[] getEnvPpkfile() {
        return this.envPpkfile;
    }
    
    public void setEnvPpkfile(byte[] envPpkfile) {
        this.envPpkfile = envPpkfile;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="envReq")
    public Set<EnvReqcomp> getEnvReqcomps() {
        return this.envReqcomps;
    }
    
    public void setEnvReqcomps(Set<EnvReqcomp> envReqcomps) {
        this.envReqcomps = envReqcomps;
    }




}


