package com.ericsson.ms.module.entity.entities;
// Generated Feb 17, 2021 5:45:34 PM by Hibernate Tools 5.4.27.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EnvReqcomp generated by hbm2java
 */
@Entity
@Table(name="env_reqcomp"
    ,schema="public"
)
public class EnvReqcomp  implements java.io.Serializable {


     private String envReqcompid;
     private EnvBbcomp envBbcomp;
     private EnvReq envReq;
     private Date envCompresubdt;
     private Date envCompcomdt;
     private String envCompstatus;
     private String envCompstatdtl;
     private String envComplink;
     private String envRepoLink;
     private Set<EnvReqspec> envReqspecs = new HashSet<EnvReqspec>(0);

    public EnvReqcomp() {
    }

	
    public EnvReqcomp(String envReqcompid, EnvBbcomp envBbcomp, EnvReq envReq, Date envCompresubdt, Date envCompcomdt, String envCompstatus, String envCompstatdtl, String envComplink) {
        this.envReqcompid = envReqcompid;
        this.envBbcomp = envBbcomp;
        this.envReq = envReq;
        this.envCompresubdt = envCompresubdt;
        this.envCompcomdt = envCompcomdt;
        this.envCompstatus = envCompstatus;
        this.envCompstatdtl = envCompstatdtl;
        this.envComplink = envComplink;
    }
    public EnvReqcomp(String envReqcompid, EnvBbcomp envBbcomp, EnvReq envReq, Date envCompresubdt, Date envCompcomdt, String envCompstatus, String envCompstatdtl, String envComplink, String envRepoLink, Set<EnvReqspec> envReqspecs) {
       this.envReqcompid = envReqcompid;
       this.envBbcomp = envBbcomp;
       this.envReq = envReq;
       this.envCompresubdt = envCompresubdt;
       this.envCompcomdt = envCompcomdt;
       this.envCompstatus = envCompstatus;
       this.envCompstatdtl = envCompstatdtl;
       this.envComplink = envComplink;
       this.envRepoLink = envRepoLink;
       this.envReqspecs = envReqspecs;
    }
   
     @Id 

    
    @Column(name="env_reqcompid", unique=true, nullable=false, length=20)
    public String getEnvReqcompid() {
        return this.envReqcompid;
    }
    
    public void setEnvReqcompid(String envReqcompid) {
        this.envReqcompid = envReqcompid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="env_compid", nullable=false)
    public EnvBbcomp getEnvBbcomp() {
        return this.envBbcomp;
    }
    
    public void setEnvBbcomp(EnvBbcomp envBbcomp) {
        this.envBbcomp = envBbcomp;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="env_reqid", nullable=false)
    public EnvReq getEnvReq() {
        return this.envReq;
    }
    
    public void setEnvReq(EnvReq envReq) {
        this.envReq = envReq;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="env_compresubdt", nullable=false, length=35)
    public Date getEnvCompresubdt() {
        return this.envCompresubdt;
    }
    
    public void setEnvCompresubdt(Date envCompresubdt) {
        this.envCompresubdt = envCompresubdt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="env_compcomdt", nullable=false, length=35)
    public Date getEnvCompcomdt() {
        return this.envCompcomdt;
    }
    
    public void setEnvCompcomdt(Date envCompcomdt) {
        this.envCompcomdt = envCompcomdt;
    }

    
    @Column(name="env_compstatus", nullable=false, length=100)
    public String getEnvCompstatus() {
        return this.envCompstatus;
    }
    
    public void setEnvCompstatus(String envCompstatus) {
        this.envCompstatus = envCompstatus;
    }

    
    @Column(name="env_compstatdtl", nullable=false)
    public String getEnvCompstatdtl() {
        return this.envCompstatdtl;
    }
    
    public void setEnvCompstatdtl(String envCompstatdtl) {
        this.envCompstatdtl = envCompstatdtl;
    }

    
    @Column(name="env_complink", nullable=false)
    public String getEnvComplink() {
        return this.envComplink;
    }
    
    public void setEnvComplink(String envComplink) {
        this.envComplink = envComplink;
    }

    
    @Column(name="env_repo_link", length=500)
    public String getEnvRepoLink() {
        return this.envRepoLink;
    }
    
    public void setEnvRepoLink(String envRepoLink) {
        this.envRepoLink = envRepoLink;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="envReqcomp")
    public Set<EnvReqspec> getEnvReqspecs() {
        return this.envReqspecs;
    }
    
    public void setEnvReqspecs(Set<EnvReqspec> envReqspecs) {
        this.envReqspecs = envReqspecs;
    }




}


